Controllers/AppointmentController.cs
using System.Globalization;
using HospitaAppointmentSystem.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HospitaAppointmentSystem.Controllers
{
    public class AppointmentController:Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly DataContext _context;

        public AppointmentController(UserManager<AppUser> userManager,DataContext context)
        {
            _context = context;
            _userManager=userManager;
        }

        public async Task<IActionResult> IndexAppointment()
        {
            var appointments = await _context.Appointments
            .Include(x => x.Doctor)
            .Include(x => x.Patient)
            .ToListAsync();
            return View(appointments);
        }

        
        [HttpGet]
        public async Task<IActionResult> GetAppointmentTimesJson(DateTime selectedDate,int doctorId)
        {
            var times = await GetAppointmentTimes(selectedDate,doctorId);
            return Json(new SelectList(times, "Value", "Text"));
        }

        private async Task<List<SelectListItem>> GetAppointmentTimes(DateTime appointmentDate,int doctorId)
        {

            var selectedTimes = await _context.Appointments
                .Where(r => r.AppointmentDate.Date == appointmentDate.Date && r.DoctorId==doctorId)
                .Select(r => r.AppointmentTime)
                .ToListAsync();

            var times = new List<SelectListItem>();
            var begin = new TimeSpan(9, 0, 0);
            var end = new TimeSpan(17, 0, 0);
            var timeInterval = TimeSpan.FromMinutes(30);

            for (var time = begin; time < end; time += timeInterval)
            {
                if (!selectedTimes.Contains(time))
                {
                    times.Add(new SelectListItem
                    {
                        Value = time.ToString(),
                        Text = time.ToString(@"hh\:mm")
                    });
                }
            }

            return times;
        }
        [HttpGet]
        public async Task<IActionResult> CreateAppointment(int? doctorId)
        {
            
            ViewBag.Doctors = new SelectList(await _context.Doctors.ToListAsync(), "DoctorId","DocNameSurname");
            ViewBag.Patients = new SelectList(await _context.Patients.ToListAsync(), "PatientId","PatientNameSurname");
            // DateTime selectedDate = DateTime.Today;
            // ViewBag.AvailableTimes = await GetAvailableTimes(selectedDate);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>CreateAppointment(Appointment model)
        {
            _context.Appointments.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }
        [HttpGet]
        public async Task<IActionResult> EditAppointment(int? id)
        {
            ViewBag.Doctors = new SelectList(await _context.Doctors.ToListAsync(), "DoctorId","DocNameSurname");
            ViewBag.Patients = new SelectList(await _context.Patients.ToListAsync(), "PatientId","PatientNameSurname");
            // DateTime selectedDate = DateTime.Today;
            // ViewBag.AvailableTimes = await GetAvailableTimes(selectedDate);
            if(id==null)
            {
                return NotFound();
            }
            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment==null)
            {
                return NotFound();
            }
            return View(appointment);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditAppointment(int id, Appointment model)
        {
            if(id!= model.AppointmentId){
                return NotFound();
            }

            if(ModelState.IsValid){
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if(!_context.Appointments.Any(o=> o.AppointmentId == model.AppointmentId)){
                        return NotFound();
                    }
                    else{
                        throw;
                    }
                }
                return RedirectToAction("IndexAppointment");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteAppointment(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            return View(appointment);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAppointment([FromForm]int id)
        {
            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            _context.Appointments.Remove(appointment);
            await _context.SaveChangesAsync();
            return RedirectToAction("IndexAppointment");
        }

    }
}

Controllers/DoctorController.cs
using HospitaAppointmentSystem.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HospitaAppointmentSystem.Controllers
{
    [Authorize(Roles = "admin")]
    public class DoctorController: Controller
    {
        private readonly DataContext _context;
        public DoctorController(DataContext context)
        {   
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Doctors.ToListAsync());
        }

        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        
        public async Task<IActionResult> Create(Doctor model,IFormFile imageFile)
        {
            var extension = Path.GetExtension(imageFile.FileName);
            var randomFileName = string.Format($"{Guid.NewGuid().ToString()}{extension}");
            var path = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot/img",randomFileName);
            if (ModelState.IsValid)
            {
                using (var stream = new FileStream(path,FileMode.Create))
                {
                    await imageFile.CopyToAsync(stream);
                }
                model.Image=randomFileName;
            }
            _context.Doctors.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
            
        }
        [HttpGet]
        public async Task<IActionResult> EditDoc(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var doctor = await _context
                                .Doctors
                                .Include(o=>o.Appointments)
                                .ThenInclude(o=>o.Patient)
                                .FirstOrDefaultAsync(o=>o.DoctorId==id);
            if (doctor==null)
            {
                return NotFound();
            }
            return View(doctor);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditDoc(int id, Doctor model)
        {
            if(id!= model.DoctorId){
                return NotFound();
            }

            if(ModelState.IsValid){
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if(!_context.Doctors.Any(o=> o.DoctorId == model.DoctorId)){
                        return NotFound();
                    }
                    else{
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteDoc(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            var doctor = await _context.Doctors.FindAsync(id);
            if (doctor == null)
            {
                return NotFound();
            }
            return View(doctor);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteDoc([FromForm]int id)
        {
            var doctor = await _context.Doctors.FindAsync(id);
            if (doctor == null)
            {
                return NotFound();
            }
            _context.Doctors.Remove(doctor);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Controllers/PatientController.cs
using HospitaAppointmentSystem.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HospitaAppointmentSystem.Controllers
{
    [Authorize(Roles = "admin")]
    public class PatientController: Controller
    {
        private readonly DataContext _context;
        public PatientController(DataContext context)
        {   
            _context = context;
        }

        public async Task<IActionResult> IndexPatient()
        {
            return View(await _context.Patients.ToListAsync());
        }
        public IActionResult CreatePatient()
        {
            return View();
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        public async Task<IActionResult> CreatePatient(Patient model)
        {
            _context.Patients.Add(model);
            await _context.SaveChangesAsync();
            return RedirectToAction("IndexPatient");
        }

        [HttpGet]
        public async Task<IActionResult> EditPatient(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }
            var patient = await _context
                                .Patients
                                .Include(o=>o.Appointments)
                                .ThenInclude(o =>o.Doctor)
                                .FirstOrDefaultAsync(o=>o.PatientId==id);
            if (patient==null)
            {
                return NotFound();
            }
            return View(patient);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPatient(int id, Patient model)
        {
            if(id!= model.PatientId){
                return NotFound();
            }

            if(ModelState.IsValid){
                try
                {
                    
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if(!_context.Patients.Any(o=> o.PatientId == model.PatientId)){
                        return NotFound();
                    }
                    else{
                        throw;
                    }
                }
                return RedirectToAction("IndexPatient");
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> DeletePatient(int? id)
        {
            if (id==null)
            {
                return NotFound();
            }
            var patient = await _context.Patients.FindAsync(id);
            if (patient == null)
            {
                return NotFound();
            }
            return View(patient);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePatient([FromForm]int id)
        {
            var patient = await _context.Patients.FindAsync(id);
            if (patient == null)
            {
                return NotFound();
            }
            _context.Patients.Remove(patient);
            await _context.SaveChangesAsync();
            return RedirectToAction("IndexPatient");
        }
    }
}

Controllers/UsersController.cs
using HospitaAppointmentSystem.Data;
using HospitaAppointmentSystem.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HospitaAppointmentSystem.Controllers
{
    [Authorize(Roles ="admin")]
    public class UsersController:Controller
    {

        private UserManager<AppUser> _userMnanager;
        private RoleManager<AppRole> _roleManager;

        public UsersController(UserManager<AppUser> userManager,RoleManager<AppRole> roleManager)
        {
            _userMnanager = userManager;
            _roleManager=roleManager;
        }
      

        public IActionResult Index()
        {
            return View(_userMnanager.Users);
        }

        public IActionResult Create()
        {
            return View();
        }
        
    
        public async Task<IActionResult> Edit(string id)
        {
            if(id==null)
            {
                return RedirectToAction("Index");
            }
            var user = await _userMnanager.FindByIdAsync(id);
            if(user!=null)
            {
                ViewBag.Roles=await _roleManager.Roles.Select(i=>i.Name).ToListAsync();
                return View(new EditViewModel{
                    Id=user.Id,
                    FullName=user.FullName,
                    Email=user.Email,
                    SelectedRoles= await _userMnanager.GetRolesAsync(user)
                });
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id,EditViewModel model)
        {
            if(id!= model.Id)
            {
                return RedirectToAction("Index");
            }

            if(ModelState.IsValid)
            {
                var user=await _userMnanager.FindByIdAsync(model.Id);
                if(user!=null)
                {
                    user.Email=model.Email;
                    user.FullName=model.FullName;

                    var result = await _userMnanager.UpdateAsync(user);

                    if(result .Succeeded && !string.IsNullOrEmpty(model.Password))
                    {
                        await _userMnanager.RemovePasswordAsync(user);
                        await _userMnanager.AddPasswordAsync(user,model.Password);
                    }
                    if(result.Succeeded)
                    {
                        await _userMnanager.RemoveFromRolesAsync(user,await _userMnanager.GetRolesAsync(user));
                        if(model.SelectedRoles!=null)
                        {
                            await _userMnanager.AddToRolesAsync(user,model.SelectedRoles);
                        }
                        return RedirectToAction("Index");
                    }
                    foreach(IdentityError err in result.Errors)
                    {
                        ModelState.AddModelError("",err.Description);
                    }
                }
            }

            return View(model);
        }

        [HttpPost]

        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userMnanager.FindByIdAsync(id);

            if (user!=null)
            {
                await _userMnanager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HospitaAppointmentSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <link rel="stylesheet" href="~/HospitaAppointmentSystem.styles.css" asp-append-version="true" />
</head>
<body >
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
        <div class="container">
            <!-- Logo -->
            <a class="navbar-brand fs-4" asp-area="" asp-controller="Home" asp-action="Index">HospitalAppointmentSystem</a>
            <!-- tggl btn -->
            <button class="navbar-toggler shadow-none border-0" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!-- sidebar -->
            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <!-- sidebar header -->
                <div class="offcanvas-header text-black border-bottom">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">HospitalAppointmentSystem</h5>
                    <button type="button" class="btn-close btn-close-white shadow-none" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <!-- sidebar body -->
                <div class="offcanvas-body d-flex flex-column flex-lg-row p-4 p-lg-0">
                    <ul class="navbar-nav justify-content-center align-items-center fs-5 flex-grow-1 pe-3">
                        @if(User.Identity?.IsAuthenticated==true)
                        {
                            @if(User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">@_localization.Getkey("Doctors").Value</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Patient" asp-action="IndexPatient">@_localization.Getkey("Patients").Value</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="IndexAppointment">@_localization.Getkey("Appointments").Value</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">@_localization.Getkey("Users").Value</a>
                                </li>
                            }
                        }
                        <ul class="navbar-nav ms-auto">
                            @if(User.Identity?.IsAuthenticated==true)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark">@_localization.Getkey("Welcome").Value, @User.Identity.Name</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">@_localization.Getkey("Logout").Value</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">@_localization.Getkey("Login").Value</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Create">@_localization.Getkey("Register").Value</a>
                                </li>
                            }
                            
                            <li class="nav-item">
                                <div class="dropdown">
                                    <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">Language</button>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="en-US" class="dropdown-item"><i class="flag-icon flag-icon-gb"></i>ENG</a>
    
                                        </li>
                                        <li>
                                            <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="tr-TR" class="dropdown-item">
                                                <i class="flag-icon flag-icon-gb"></i>TR
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
    $(document).ready(function () {
        // Dil seçimi için event handler tanımla
        $('.dropdown-menu .dropdown-item').on('click', function () {
            var selectedLanguage = $(this).text();
            // Buton metnini seçilen dil ile güncelle
            $('.dropdown-toggle').text(selectedLanguage);
            // Seçimi localStorage'a kaydet
            localStorage.setItem('selectedLanguage', selectedLanguage);
        });

        // Sayfa yüklendiğinde, daha önce seçilmiş dili kontrol et
        var savedLanguage = localStorage.getItem('selectedLanguage');
        if (savedLanguage) {
            // Kaydedilmiş dil varsa buton metnini güncelle
            $('.dropdown-toggle').text(savedLanguage);
        }
    });
</script>